### ISSUE TITLE
One Stop Mental Health Resources

### ISSUE THREAD

**Issue by scribblerjane** [sketch-city/project-ideas#109]
There is more mental health awareness today than ever before. But there is still a stigma surrounding admitting that we need help.
There is also the different levels of mental health ranging from anxiety to depression to schizophrenia.

Can we create a one stop solution where a person can search by their need for local resources like self-help, group therapy, best therapist, etc? 

And how can we encourage a more open dialogue about our most vulnerable and hidden secrets, "Hi, my name is Jane, and I experience anxiety and shame."

**Comment by meremaines** [comment]
Jane!!! I just published another idea that would be similar! And it has a subject matter expert! Interested in rolling the ideas together? https://github.com/sketch-city/project-ideas/issues/115

**Comment by scribblerjane** [comment]
Meredith! That sounds fantastic! I definitely see the overlaps.

**Comment by fileunderjeff** [comment]
Closing this thread to merge with #115.
