### ISSUE TITLE
Human trafficking campaign

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#11]
Using craigslist and back page as sources, how can we measure human trafficking demand in Houston?
Another project would be to create a website to educate the public about human trafficking in Houston.

**Comment by juyeongkim** [comment]
I really like these ideas!

I know [A 2nd Cup](https://munchies.vice.com/en/articles/fighting-human-trafficking-one-cup-of-coffee-at-a-time), a non-profit coffee shop fighting against human trafficking issues in Houston, does not have a website yet. They only have [a landing page](http://www.a2ndcup.com/). This website could have both information about the coffee shop and human trafficking issues in Houston.

If anyone is interested in pursuing this, I can connect you to Erica, the founder of A 2nd Cup!

**Comment by srigdon** [comment]
Info & resources for anyone interested in this project: 
- [Turner takes aim at curbing human trafficking](http://www.houstonchronicle.com/news/houston-texas/houston/article/Turner-takes-aim-at-curbing-human-trafficking-7423847.php) by Rebecca Elliott and Lomi Kriel for the Houston Chronicle 
- [The City of Houston and the Houston Area Council on Human Trafficking (HACHT) joint initiative](http://humantraffickinghouston.org/) 
- [United Against Human Trafficking](http://uaht.org/)

**Comment by fileunderjeff** [comment]
The City of Houston released [this strategic plan](https://github.com/sketch-city/project-ideas/files/256217/Human-Trafficking-Strategic-Plan.pdf) today. 

My company also did [some research](http://ht.januaryadvisors.com) into tech and human trafficking a few months ago.

**Comment by CarlaCarlaBoBarla** [comment]
It would be awesome if some expert level coders can join this team because I love the subject but don't know how to code :-(

**Comment by CarlaCarlaBoBarla** [comment]
[2016 Sex Trafficking and Events Study (2).pdf](https://github.com/sketch-city/project-ideas/files/263424/2016.Sex.Trafficking.and.Events.Study.2.pdf)

**Comment by coffeyhaus** [comment]
Hi all! I've been involved with A 2nd Cup from the beginning, and I happen to know that its website is in the final stages of being launched. It does include information about the coffee shop as well as connecting its patrons to resources about human trafficking.

**Comment by fileunderjeff** [comment]
Closing this issue as the John's Beware team is still active and working on this and related projects.
