### ISSUE TITLE
Is today an election in Houston?

### ISSUE THREAD

**Issue by rmoscowitz** [sketch-city/project-ideas#113]
**Website**
- Very basic YES / NO depending on the Harris County election calendar
- Basic ballot info
- Links to more info

**Widget**
- Embeddable version of YES/NO election day site.

**Textbot**
- @fileunderjeff mentioned that this has been prototyped:
  - Text SOMEWORD to SOMENUMBER to get text alerts
  - You receive a text when early voting starts, when early voting ends, on election day, and after election day asking if you voted.

**Comment by fileunderjeff** [comment]
@mahopa @judopp check it ^^

**Comment by judopp** [comment]
This idea overlaps the purpose and long range goals of VOTExt (see #league_women_vtr_sms Slack Channel correspondence).  The software that Alex Miller wrote puts subscriber/voters on a list for receiving text reminders about voting dates and times along with important links about polling places.  The project, as envisioned by the League of Women Voters, was a way to drive traffic to their web-site where information about the candidates would be posted.  

We just finished a small test of our code in the recent Pasadena Municipal Elections.  If you are interested in helping us and/or signing up to see how it works (for the runoff), go to the slack site.  A larger, more systematic rollout will be in November for the School Board elections.

**Comment by rmoscowitz** [comment]
Very cool, I'll join the slack channel. I'm interested in testing/helping out after the hackathon. 😃
