### ISSUE TITLE
Houston E-Library Portal

### ISSUE THREAD

**Issue by rmoscowitz** [sketch-city/project-ideas#114]
Houston residents can check out digital media from a number of different services provided by multiple library systems. This project seeks to provide a simpler method for accessing digital resources.

**Hackathon**
* How to get library cards!
* How to use e-books
* Both [Houston Public Library](https://hadc.overdrive.com/hadc-houstonpublic/content) and the [Harris County Public Library](https://hcpl.overdrive.com/) use Overdrive to provide access to e-books and audio books. For the hackathon, let's utilize [Overdrive's Discovery API](https://developer.overdrive.com/discovery-apis) to at least create a unified search experience.
* English & Spanish

**Long Term**
* checking out/returning with [Overdrive's Circulation API](https://developer.overdrive.com/circulation-apis)
* incorporate other library systems like Fort Bend County Library
* explore other services like Hoopla
* Related suggestion from @fileunderjeff: freedom of information act request for inventory of both systems to analyze usage / find redundancies

**Comment by fileunderjeff** [comment]
this is such a good idea

**Comment by zenjen777** [comment]
Totally agree...as an MLIS, needless to say I love this idea! 😊

Jen Greer

**Comment by rmoscowitz** [comment]
How to get a library card...

**Houston Public Library** (must be a Texas resident)
- [MY Link](http://houstonlibrary.org/library-card-registration) - apply online

**Harris County Public Library** (must be a resident of Harris County)
- [iKnow Digital Library](https://ecard.hcpl.net/Ecard/ecard.php) - apply online ([more info](http://www.hcpl.net/iknow))
- [Knowledge Card (full service)](http://www.hcpl.net/about/library-cards) - full service, must apply in person or by mail

**Comment by meremaines** [comment]
Oh awesome! I thought you had to be a Houston resident for a HPL card. I'm in Fort Bend, but if "Texan" is the only qualification, I need to go get a card! :)

**Comment by rmoscowitz** [comment]
@meremaines Try it out (and let me know how it goes)!

I just looked at the Fort Bend County LIbrary and apparently they say the same thing! "To get your free, permanent library card, bring a government-issued photo ID and proof of Texas residency within 30 days of receiving this temporary number. Out-of-state residents must pay a fee for the permanent card." I may have to get a FBCL card too! 😄 

I didn't have the same luck with Dallas, Fort Worth, Austin or San Antonio. They **_all_** say you must be a resident of that specific area.

I also discovered this: "Non-Residents can apply for a free limited access Library Card by presenting their current/valid [TexShare card](https://www.tsl.texas.gov/texshare/card ) from a participating library system." Might be worth investigating later.

**Comment by meremaines** [comment]
@rmoscowitz awesome, I'll try it! Glad Houston gets to claim the inclusiveness award. Hahah!

**Comment by antonywu** [comment]
Also, just want to mention that Houston Public library has access to Lynda content for free
[http://lynda.com/portal/sip?org=houstonlibrary.org](http://lynda.com/portal/sip?org=houstonlibrary.org)

**Comment by rmoscowitz** [comment]
I'll be working on this project for the 2017 hackathon! I'll be in `#elibrary-portal` on slack and welcome help/pointers/opinions.

**Comment by betterways** [comment]
Overdrive is terrible. Can we use the API to make something much more useable?   HooplaDigital works much, much  better, but they don't offer an awful lot of audiobooks you'd think they'd have, i.e. Malcom Gladwell's books.  And the hoopla app can't be installed on my older android phone that I'd like to give to my grandmother as a player.

**Comment by rmoscowitz** [comment]
@betterways, I agree that the Overdrive app is _terrible_ (I basically only use their website now). For this weekend, I'm planning on using Overdrive's data (hence the API) and making a (hopefully more user-friendly) alternative. 

Also thanks for the vote for Hoopla! I haven't used it before, but I noticed they also have an API and might be a good service to integrate in the future.

For this weekend, I'm not sure we'll tackle anything mobile. However, I'm really curious how other people consume digital media from the library. Will you be at the hackathon? I'd like to ask you about how you (and your grandmother) use it.

**Comment by palasaram** [comment]
@rmoscowitz 
Really cool project. 
Do you have approval/license to use the  Overdrive's Discovery API ?

![developer portal discovery apis](https://cloud.githubusercontent.com/assets/28811364/26257081/d9e01360-3c84-11e7-901d-873cc89a61ba.png)

**Comment by rmoscowitz** [comment]
Yes! I have this level (for now):

> Client authentication gets you access to our Discovery APIs only. If you're only going to use the OverDrive APIs to search a collection, access title metadata, or retrieve availability information for specific titles, the Discovery APIs should suit your needs. This level of access does not allow you to let users place holds or borrow titles from an OverDrive digital collection. If you would like to use our integration test library (optional), you'll need to request access.

I just tested it out, I was able to successfully make requests to the Library, Search, Metatdata and Availability endpoints for both Harris Co & Houston.

**Comment by rmoscowitz** [comment]
We're up and running!

Code: https://github.com/rmoscowitz/houston-elibrary-portal
Site: http://houstonbook.link/
