### ISSUE TITLE
Mental Health tech ideas (mobile app, one-stop web portal, etc.)

### ISSUE THREAD

**Issue by meremaines** [sketch-city/project-ideas#115]
1 in 4 children have a diagnosable mental illness, but only 20% receive treatment in any given year. We want children to have access to information about mental illness and help reduce the stigma around mental illness so that people are more likely to get help.

Our friends at Houston's Mental Health America (MHA) office think **a mental health app for teens** would be extremely helpful. There are a variety of apps available, but many of the good ones cost money. We would want the app to potentially be game-ified and help youth learn about prevalence data, signs and symptoms, etc. We'd also like to have local resources included. MHA has a Resource Guide for youth behavioral health, so those resources could be used.

MHA can provide the behavioral health information needed—statistics, signs and symptoms, resources, etc. And if the project takes off, MHA would definitely market it and help get it into schools.

Scope:

- app for teens
- possibly game-ified
- info on signs, symptoms
- list of local resources
- data available from MHA

Check out this link for more info: http://www.mhahouston.org/the-center-for-school-behavioral-health/
This project has a dedicated subject-matter expert, so if you're interested, I can put you in touch!

**Comment by fileunderjeff** [comment]
From #109 by @scribblerjane: "There is more mental health awareness today than ever before. But there is still a stigma surrounding admitting that we need help.
There is also the different levels of mental health ranging from anxiety to depression to schizophrenia.

Can we create a one stop solution where a person can search by their need for local resources like self-help, group therapy, best therapist, etc?

And how can we encourage a more open dialogue about our most vulnerable and hidden secrets, "Hi, my name is Jane, and I experience anxiety and shame.""

**Comment by nnpereira** [comment]
This sounds awesome and I'd love to help! @meremaines could you please put me in touch with the subject-matter-expert tied to this project? I'd also love to see what kind of data MHA currently has :)

**Comment by keniasalazarm** [comment]
I´m really interested in this subject too. I believe many positive things can be achieved by only being aware about our nature and behavioral health, specially at a young age. I would love to help @meremaines

**Comment by LawExplorer** [comment]
If it is relevant, this is a resource that the Bureau of Justice Assistance offers for "Police-Mental Health Collaboration": [https://pmhctoolkit.bja.gov/?utm_source=redirect&utm_medium=web&utm_campaign=PMHC](https://pmhctoolkit.bja.gov/?utm_source=redirect&utm_medium=web&utm_campaign=PMHC).

**Comment by antonywu** [comment]
I am aware there is a stigma around mental health, but we definitely have more exposure on mental health in media than before. Personally, I think another issue at hand is the availability of quality treatment and caring staffs to those mental health patients.

Too many times I read reviews on Houston's local mental health facilities, and how poor the treatments that patients received. Sleeping on the benches, non caring doctors and neglect by staff run rampant. Maybe we need a review by patients to promote the best mental health facilities in Houston area. Sadly reviews for Harris County Psychiatric Center and NPC next to Ben Taub have quite a bit of horror stories on the Internet.

**Comment by meremaines** [comment]
FYI: a Slack convo is starting for this project, "#mentalhealth," so feel free to join over there if you're interested!

**Comment by ciscohdz** [comment]
This is something I have thought about before but more along the lines of injury rehab.  This sounds like a great project.  

I can't attend the hackathon but I'm willing to help.

**Comment by mralexcraven3** [comment]
@meremaines I would love to help, I was looking online/github at ideas for a mental health app, and  came across this! How do I join in if it's still possible?
