### ISSUE TITLE
Smoke Detector Risk Model

### ISSUE THREAD

**Issue by stevenrdavid** [sketch-city/project-ideas#116]
There was a recent collaboration between New Orleans and a company called Enigma that focuses on identifying, through census data, homes that have the highest risk of not having a smoke detector/alarm. They worked through the difficulty of gathering solid data sets (a routine problem of the City of Houston) and were able to hammer out a risk model that went as narrowly as the block group. This allowed New Orleans FD to prioritize their limited budget to the highest risk homes, and rollout and awesome program. Fortunately for us, the data and logic behind their weights were made public with the hope that other municipalities would use it. Part of that logic is to calculate a 'population risk' which determines the likelihood of a citizen in the block group being over 65 years old and under 5 years old.

The risk model, calculated in R, has been made available to the public. I want to re-create this model for the City of Houston, but also add disability status to the calculation.

https://github.com/enigma-io/smoke-signals-model

**Comment by fileunderjeff** [comment]
@stevenrdavid dude, i'm in! tagging other R ppl who would be into it: @neerajt @pandafulmanda @jpoles1 @juyeongkim. also going to share in the HRUG slack channel.

**Comment by fileunderjeff** [comment]
@stevenrdavid do you (or does the census data) have disability information at the block group level?

**Comment by stevenrdavid** [comment]
We don't, but that is where this project is going to be fun. There are ways to logic to whether or not a person is part of the disabled community by looking at medicaid and SSI information.


SD

________________________________

**Comment by naiverav** [comment]
I am a budding R coder and would love to get involved, can I be a part of this group please?
Rav

**Comment by stevenrdavid** [comment]
Heck yea! I look forward to meeting you.


SD

________________________________

**Comment by naiverav** [comment]
hey @stevenrdavid, are you already at HTC?

**Comment by stevenrdavid** [comment]
Parking now.

Sent from my iPhone

On May 20, 2017, at 11:04 AM, naiverav <notifications@github.com<mailto:notifications@github.com>> wrote:


hey @stevenrdavid<https://github.com/stevenrdavid>, are you already at HTC?

**Comment by oliviadurr** [comment]
I'm really interested to hear how this project is going! (Found it through Sketch City's Meetup page). I've been looking for projects where I can contribute business/marketing skills while learning more about the work of developers/designers/data scientists. Plus, my family is in the electrical business, so I'm especially happy to see others care about electrical safety. Are y'all still working on this?
