### ISSUE TITLE
A site/project to compare property taxes and real estate costs of various neighborhoods

### ISSUE THREAD

**Issue by matthiasak** [sketch-city/project-ideas#118]

**Comment by antonywu** [comment]
and by real estate costs, you mean recent sold price? and who is the main audience to use this? home owners? or HCAD?

**Comment by fileunderjeff** [comment]
@matthiasak @antonywu I could imagine a useful project that:

1. takes the HCAD assessment values of the neighborhood and 
2. cross-references it with recent listings on the MLS and
3. maybe cross-references it with Zillow's "zestimates" and
4. shows you the difference between the assessments and the market value -- maybe at a neighborhood or census block level?

**Comment by fileunderjeff** [comment]
@antonywu in terms of the audience, as a homeowner, i would use it to better make a case when i protest my property tax hikes.

**Comment by matthiasak** [comment]
@antonywu @fileunderjeff I dont think the idea should be limited by whom it is meant for/targeting; I think I might actually prefer to keep it pretty generic for comparing datasets from various sources; first use case would be perhaps compare any attribute of real estate costs, not just purchase price. If it is useful, homeowners could use it to fight the rising costs of owning a home, and HCAD might be able to accurately use it (although I suspect they have a host of data and tools somewhere that they use to appraise property values.)

**Comment by emptyflash** [comment]
I worked on a team doing this at last year's hackathon (we didn't quite finish): https://github.com/philellsworth/Vital-Houston

(also I think the original repo go deleted, that's a fork with old code, I have the code on my local machine if anyone is interested)

**Comment by matthiasak** [comment]
I was thinking it looked a bit minimal :) yea, anything that can be used to learn from, build on would be cool

**Comment by busybiee** [comment]
Cool i like the project. I ll take a look at github, hopefully we can do this event better.
