### ISSUE TITLE
Homeless resource locator - AskIzzy clone for the US

### ISSUE THREAD

**Issue by muhsackio** [sketch-city/project-ideas#121]
[AskIzzy](https://askizzy.org.au/) is a great resource locator for those who are homeless or are in danger of becoming homeless. The only problem is that it's exclusive to Australia. I'd like to bring it to the US. The goal is to extend information already stored in the Google Places database to include tags describing what types of services can be found at each location. Then, each location would be placed in a certain bucket and rendered under the appropriate category, a la AskIzzy.

I've got some groundwork laid for an app built with [Google Polymer v1](https://www.polymer-project.org/), but would be fine starting from scratch as well.

**Comment by dylanjbarth** [comment]
@neerajt seems up your alley

**Comment by mztran** [comment]
Awesome idea. How can I get involved and help?

**Comment by ghost** [comment]
Hi,
Askizzy is a frontend for http://www.serviceseeker.com.au

I would like to have someting like that in Brazil.
If, i would use https://sourceforge.net/projects/cyclos/files/?source=navbar to prorotype it.
The best would be to make it tailores for SUAS management, i guess http://www.mds.gov.br/assuntos/assistencia-social/gestao-do-suas/sistemas-de-informacao-da-rede-suas

Regards,
