### ISSUE TITLE
Remote Vote - Increasing voter turnout

### ISSUE THREAD

**Issue by ausjm** [sketch-city/project-ideas#123]
Would love to see this piloted here in Houston.

**Problem:** Long lines, limited locations, and access to transportation are all barriers citizens face during elections.

**Deliverable:** Create a web or mobile based platform for Harris County polling. Fact only information on issues & candidates ie: Politician voting records, # of people impacted by issue, etc..

**Stretch Goal:** Notification system for upcoming polls.

**Hurdles:** Identity verification, ballot integrity (double voting), server security, hesitant public.

**Comment by fileunderjeff** [comment]
Check out [Dr. Dan Wallach](https://www.cs.rice.edu/~dwallach/) - he's the expert! Lots of good links there.

**Comment by judopp** [comment]
So many people have been relocated from the floods that their voter status could be brought in to question.  Someone needs to get ahead of this issue before the usual Voter-ID suspects start questioning whole neighborhoods.  Maybe this development is the tipping point that pushes this strategy/idea to the forefront.
