### ISSUE TITLE
App to for quick response for volunteer requests which have a time constraint - like food donations.

### ISSUE THREAD

**Issue by betterways** [sketch-city/project-ideas#126]
Such as for the charity organization 2nd Servings.  They get leftover prepared food picked up & taken to facilities where they are shared.  

https://www.secondservingshouston.org/

**Comment by SijieC** [comment]
I am interested in exploring more of this idea! Are you at the Hackathon right now?

**Comment by sreeku44** [comment]
We are 2 iOs developers working on iOS/ iPhone app for "volunteer  requests which have a time constraint"
