### ISSUE TITLE
High Risk Vehicle Accident Area App

### ISSUE THREAD

**Issue by malexrodtech** [sketch-city/project-ideas#127]
Our idea is to build an Android or Web app which alerts a driver/pedestrian when they enter an area of high traffic accidents. The statistical data is provided by the TxDOT website's CRIS query tool.

**Comment by sreeku44** [comment]
Hi,
I am interested in this project ,  but I am an iOS developer. I can do this iOS / iphone .Thoughts / comments please .

**Comment by sreeku44** [comment]
Hi,
I am interested in this project , But I am an iOS developer . I can make an
iOS app for this project . Your thoughts / Comments please .

Regards,

Sreeku

**Comment by malexrodtech** [comment]
I'm in a gray polo shirt in the back

**Comment by ghost** [comment]
This sounds like an awesome project! I would like to get involved. Are there any updates?
