### ISSUE TITLE
Neighborhood Anthropology

### ISSUE THREAD

**Issue by LawExplorer** [sketch-city/project-ideas#128]
How and when were our respective neighborhoods created?  What was there before?  Who lived there in the past?  Why have our neighborhoods changed over time?  
Many of us know little if anything about the history of the neighborhoods in which we live.  There should be some maps of the different parts of Houston at various times in the past, and perhaps some data is available from census and property records to tell us something about the people who lived in the various neighborhoods.  Historical information is probably available from public or university libraries as well as some civic groups.
The objective of this project is to enhance our appreciation for our own neighborhoods as well as other neighborhoods around the City of Houston.

**Comment by fileunderjeff** [comment]
@LawExplorer i had an idea to text mine obituaries and correlate them to the locations of funeral homes to determine what kinds of people lived in what neighborhoods. maybe we could collaborate!

**Comment by LawExplorer** [comment]
Yes, that would be cool, @fileunderjeff.  Obituaries will likely produce some significant indicators.  This issue is a product of some of the conversations during the event last Friday evening at TXRX Labs.

**Comment by meremaines** [comment]
Wish we could research the people then, and turn their stories into a podcast, too!

**Comment by LawExplorer** [comment]
Some oral histories may have been preserved during the New Deal era, @meremaines.  Other sources of relevant information might include the [Texas State Historical Association](https://www.tshaonline.org/home/) or the [Houston History Alliance](https://www.houstonhistoryalliance.org/).  Historical maps of the changing names and boundaries of Houston's neighborhoods might be cool also.

**Comment by LawExplorer** [comment]
Here are links to some of the maps of Houston that are available online, although I do not know how much useful information they contain about specific neighborhoods.  The Library of Congress has a couple of old ones from, respectively, [1891](https://www.loc.gov/resource/g4034h.pm009150/) and [1912](https://www.loc.gov/resource/g4034h.pm009160/).  The [Texas State Library and Archives Commission](https://www.tsl.texas.gov) has [fire insurance maps](https://www.tsl.texas.gov/arc/fim-customSearch).

**Comment by LawExplorer** [comment]
The [Houston Oral History Project](http://www.houstonoralhistory.org) might have some relevant interviews, and a number of oral histories are [available online](http://digital.utsa.edu/cdm/search/searchterm/Institute%20of%20Texan%20Cultures%20Oral%20History%20Collection!houston/field/all!all/mode/exact!all/conn/and!and) from the University at San Antonio.

**Comment by poprox** [comment]
I've seen a lot of historic aerial photos in the past at various government organizations, I'm unsure if the City of Houston or Harris County have historic aerial photos, but I can reach out to some contacts on that.

With modern mapping technology, you can take these old photos or old paper drawn maps and overlay them on the earth relative to where they would be in the real world.

See this example of an old Houston map from 1900 from the Texas General Land Office -http://arcg.is/2qrEQvT

I'll reach out to some local folks at Harris & Houston to see if they may have old photos or maps as well we could use in a simple map interface to see how things have changed over time.

**Comment by LawExplorer** [comment]
One of the intriguing items on the map, @poprox  is the name of the surveyor, "Whitty."  A search of Google for that name turned up a number of results, one of which is a thread on the forum of the website [RLPS Today](https://rplstoday.com/).  That thread, "[The Curious Case of the Houston Code](https://rplstoday.com/community/threads/the-curious-case-of-the-houston-code.327429/)," contains references to maps and other materials as well as a partial list of surveyors.
One or more court opinions might help shed light on the contexts and implications of different maps.  I will search the next time I visit one of the local law libraries.  The [City of Houston GIS Portal](http://mycity.houstontx.gov/home/) has some cool maps such as this one of [annexation history](http://mycity.maps.arcgis.com/apps/MapJournal/index.html?appid=0f1a558e6f7548678323c82173b90239).

**Comment by lanzhenw** [comment]
I once saw a very impressive digital humanities project called "On-Broadway" (http://www.on-broadway.nyc/). It pulls data from uber and instagram pictures and correlate them with their location on the street of Broadway. But that gears towards the contemporary culture of 21st century city space of Manhattan. 

For historical pictures of Houston, I know Houston Chronicles would from time to time post old pictures about Houston downtown.
