### ISSUE TITLE
App for the Houston Hackathon

### ISSUE THREAD

**Issue by LawExplorer** [sketch-city/project-ideas#130]
Hackathons produce apps, but can an app be produced for the Houston Hackathon?  Such an app might help participants navigate the hackathon while the event is in progress and include information about the active projects with some sort of search function based on keywords.
The example that I have in mind is the mobile app for SXSWedu (http://sxswedu.com/mobile).  It was quite helpful and easy to use when I attended that event a few years ago.

**Comment by BryanH** [comment]
Very doable. We could do something simple like show RSVP'd (from Meetup) peeps, list of active projects from GitHub. Anything else?

**Comment by LawExplorer** [comment]
That is a good foundation, @BryanH !  I wonder whether it would be a bridge too far to update the status of different projects during the event.

**Comment by BryanH** [comment]
I'm thinking something automated, because no one has time to manually update status!

We could track last github push, for starters.
