### ISSUE TITLE
City of Houston Employee Roster

### ISSUE THREAD

**Issue by frank0051** [sketch-city/project-ideas#133]
Posting the City of Houston Employee Roster that was previously made available online in 2016 for nearly a year here. The roster had been made available on the Internet for public consumption starting in June 2016 and was directly accessible through the Open Data Portal until at least July 2017. The employee roster itself is still available online at using an Internet archive to get to the file. I am posting it here to preserve the record. 

[links redacted]

**Comment by fileunderjeff** [comment]
Hi Frank, at the City of Houston's request, I had to redact those links. I would encourage anyone with an interest in this data to contact you directly. My apologies for any inconvenience.

**Comment by frank0051** [comment]
I'm disappointed in Sketch City choosing to remove legally valid information that was legally released by the City into the public domain with zero liability placed on any entities or individual holding the data. 

To re-post  in a way that shows the public domain nature of the documents, the information is available on the Internet Archive as re-hosted from the _**official**_ City of Houston website at:
https://web.archive.org/web/20160704044935/http://houstontx.gov/finance/Open%20Data%20Site/COH%20Employee%20Roster%20-%202016-06-01.xlsx

Metdata is available at:
https://web.archive.org/web/20160704044935/http://data.ohouston.org:80/dataset/city-of-houston-current-employee-roster/resource/98448c04-e76f-4fa0-8916-12786e6e5883

Description available at: https://web.archive.org/web/20160704044935/http://data.ohouston.org:80/dataset/city-of-houston-current-employee-roster

I have requested a new, updated version where names of certain individuals will be redacted. Appearing as the City does not intend to post it up, I will pay for it and post it up here as well.
