### ISSUE TITLE
Mental Health hack night notes and project prompts

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#135]
These are my notes from the Mental Health hack night on 11/14/2017. It contains information about [Mental Health America of Greater Houston](http://www.mhahouston.org) and their needs.

Questions driving MHA's programs (how might we...):

- bring accurate, up-to-date information and resources to youth and families?
- reduce stigma and fear of mental health issues in the youth population?

Because it can take 8+ years to diagnose a mental illness, many children will have symptoms but not be diagnosed until young adulthood. Therefore, MHA is looking to find patterns and indicators to better treat adolescents.

The data addressing mental illness is often outdated and abstracted. There is a need to get better, more specific records. It would be helpful to develop a list of available data sources, as well as places that might be collecting useful data. Many schools don't track mental health referrals. Many schools in Houston ISD don't have a full time school nurse.

MHA wants to create a "Community Knowledge Management System" that is open and available to the public, and contains resources, data, information, trainings, and coordination. [Here is a directory that could be a jumping off point](http://www.mhahouston.org/media/files/files/ce74590c/The_Guide__2015-17_FINAL_PDF_Rotated.pdf). It would be more than a directory of services; it would be an "entrance" to finding additional mental health assistance. It could also help the various mental health partners share information and data.

Uses the United Way 211 directory for service providers, but found it very frustrating to navigate. Would want something that can guide you to the services that you need. Might have service providers in addition to the 211 providers; would need to merge them.

Needs a better way to document the programs that their partners (e.g. HISD) are running about mental health. Currently, it's collected manually and it's very time consuming.

**Comment by fileunderjeff** [comment]
Very interested in delivering these services using low cost technology.

**Comment by johncblandii** [comment]
They talked about an app. What would this app do? Where does the data come from? I assume the CKMS.

**Comment by fileunderjeff** [comment]
@johncblandii yes, I think it's a matter of picking a single use case and exploring it in greater depth. For example, Betsy talked about partner training. If they focused on a tech solution for delivering training, it might be narrow enough to develop a prototype without bucking under the weight of these requirements. From what I can tell, they have not prioritized the use cases yet, so it is unclear where to begin.

**Comment by fileunderjeff** [comment]
Another idea: many schools don't track mental health referrals. Develop a digital "best practices" document for how schools should handle mental health referrals.

**Comment by johncblandii** [comment]
What about some repository for a consistent way of adding data?

I guess I'm thinking sort of like a nosql db where the fields could be adjusted, but with a consistent starting structure for a semblance of normalcy. Someone with more time or a contract could take the chance to push this to the next level of building out adapters for data dumps to feed data in at regular intervals.

It could be one huge repository or individual installs, but it seems one with strict permissions on the data would make it easier to share it between schools.
