### ISSUE TITLE
Houston Pollen and Mold Alert App

### ISSUE THREAD

**Issue by emptyflash** [sketch-city/project-ideas#137]
It's allergies season, and this year has been one of the worst in a while.

The Houston Health Department puts out a daily pollen and mold count: 
http://www.houstontx.gov/health/Pollen-Mold/index.html

I think it'd be nice if we had an app that gives people alerts based on the specific thing they're allergic to (Species of tree pollen, grass/weed pollen, and mold pollen).

Unfortunately the pollen index gets updated daily around 10 AM, and doesn't get updated on weekends and holidays. 

I think this could potentially be a good fit for some statistics and ML people to predict a day into the future and give people timely alerts. It would also be a good project for people with experience in scraping, and web development (for the app part).

I've already made a channel in Slack, #allergeez, and posted some info in there. 

I've also start cleaning up some of the historical data so that anyone interested in doing a pollen related hackathon project can use it: https://github.com/emptyflash/houston-pollen-data

**Comment by alankjackson** [comment]
The predictive sounds interesting to me. I started pulling some papers off the web, and it looks complex. I may take a crack at it this summer. Apparently, the controls on pollen release vary by species and there are a number of weather-related factors that are important. Having run my own weather station for years, I know where to get that data. 8-) I suspect the tricky bit will be that it will depend on aspects of the weather history (hours above some temperature, light rain two days earlier, etc).

**Comment by emptyflash** [comment]
yeah, I've tried messing around with the data a little bit to see if I can get a semi-decent model to work, with not much luck. I have no doubt adding some other features like weather (high temp, low temp, precipitation, humidity, future forecast) would improve accuracy a lot. The historical data isn't super clean, so I think that might be another challenge.

**Comment by alankjackson** [comment]
I'm thinking that for my strategy, I'll first develop some statistics on what the most important species are by volume of pollen and number of days, and then research the biology of those to see what the important factors are likely to be. Although another approach for a 1-2 day forecast might be to do something really simple like a Kalman filter, but split it out by species.

**Comment by emptyflash** [comment]
That sounds like a great idea! I'd love to talk more about it, the #allergeez channel in the Sketch City slack is a great place to chat. I'll also be at the Sketch City meetup tomorrow.

**Comment by emptyflash** [comment]
We did it:
https://allergeez.me
https://devpost.com/software/allergeez
https://github.comemptyflash/allergeez
