### ISSUE TITLE
Plastic: It's What's for Breakfast, Lunch, and Dinner!

### ISSUE THREAD

**Issue by iamespike** [sketch-city/project-ideas#138]
Styrofoam to-go containers, plastic forks, straws, plastic bags are persistent and toxins stick to them.  Best case scenario plastics go to landfills where they take up space, never decompose, and contribute to methane production---a strong greenhouse gas.  Worst case scenario, plastics accumulate in one of the many plastic garbage patches in the ocean where we get our seafood.  They never breakdown, they adhere to toxins like DDT, PCB, etc and move through the food chain to be eaten by people. The Washington Post reports more plastic will fill our oceans than fish by 2050, see https://tinyurl.com/y7hf3hy7

What can we do to reduce our plastic consumption?  Make an app that rates restaurants by how much plastic they pass on to customers.  I've got data, see my form here: https://goo.gl/forms/RmSBgowu6A8glbJs2. Together we can build an app to help customers avoid single use plastic when they eat out.  We want a good meal without poisoning the planet.  Let's make smarter choices with our wallets.

**Comment by fileunderjeff** [comment]
Hi @iamespike! This is super awesome. Do you have a link to the dataset itself? I'm going to post this to slack.

**Comment by iamespike** [comment]
Here is google spreadsheet:
https://docs.google.com/spreadsheets/d/1SnGKKD-e3U8UNUMJN5-rcpvBJqtvxdDnnDJwKbhfoAU/edit#gid=1173114207

**Comment by sya** [comment]
@iamespike this is awesome!
I'd love to share this on data.world. Would you say this data is in the Public Domain??

**Comment by iamespike** [comment]
Thanks, not yet.  Not entirely sure what public domain means.
