### ISSUE TITLE
Intro to City of Houston website

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#141]
What does the City of Houston do, and how does it work? It would be great to have a website that explains the way that the city operates, and how citizens can get involved. 

Here are some examples of pages that might be helpful:

- Capital improvement projects - what are they, how are they planned, and why are they important?
- Houston's strong mayor form of government - how does Houston's executive administration work? what do City Council members do?
- Org charts - key staff positions and what they do
- Key programs - in plain language, describe what they are and list key city or administration programs (e.g. Harvey recovery programs, Complete Communities, etc.)
- City budget - how does it work? what does it mean?
- Speaking at public comment session - how to do it, why to do it, proper etiquette

It could be a directory site, but it could also be a workflow starting with what people care about.

**Comment by LawExplorer** [comment]
A wiki could can serve those purposes.  With [Semantic MediaWiki](https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki), administrators and even users can import structured data.  The wiki farm [Referata](http://referata.com/wiki/Main_Page) permits the creation of a semantic wiki for free, so that would be one way to create a prototype.

**Comment by LawExplorer** [comment]
Here are some links to information about plain language in law and government:

- [Plain Language](https://www.plainlanguage.gov/) website for the U.S. Government;
- [Writing Tips](https://www.scribes.org/writing-tips) and [Grammar Tips](https://www.scribes.org/grammar-tips) from the [American Society of Legal Writers](https://www.scribes.org/);
- Publications from the European Union
- _[How to Write Clearly](https://publications.europa.eu/en/publication-detail/-/publication/c2dab20c-0414-408d-87b5-dd3c6e5dd9a5/language-en)_
- _[Claire's Clear Writing Tips](https://ec.europa.eu/info/files/claires-clear-writing-tips_en)_.

Books by Rudolf Flesch also provide guidance about plain language.  A couple of those titles are _The Art of Plain Talk_ and _The Art of Plain Writing_.
