### ISSUE TITLE
Census 2020 undercount outreach - digital tools and community campaigns

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#146]
From the Mayor's office and partners:

> Houston’s Census Undercount is driven by immigrant and low income communities, making up to 30% of our regional population invisible, costing us $ billions in federal support due our region for health, safety, mobility, infrastructure and equitable political representation.  Immigrant families comprise up to 40% of our region’s demographics.  Language is an issue.
> 
> How can we build digital communications architecture for safe information sharing in communities at high risk of undercount, those families fearful of responding to the census.  2020 Census will be the first time there will be can online option for Census response.
> 
> How can we engage students to lead in an organic, “bubble-up” response campaign to get their own families counted?
> 
> How can we build a safe 2-way communications network that guarantees the security / anonymity of potential ‘trusted voices” in our neighborhoods?
> 
> How can we link student field work in neighborhoods, identifying ground level demographics and customized communications strategies with https://www.census.gov/roam?

**Comment by davidmcclendon** [comment]
I'd love to be a part of this project. I've got a background in demography and extensive experience with the census and American Community. I can contribute ideas, background knowledge, and analysis. Two potential add-ons to this project that would be valuable would be 1) to estimate the potential impact of the citizenship question on response rates (by comparing 2010 census and 2011 American Community Survey), 2) begin to estimate the economic impact of an undercount on communities.
