### ISSUE TITLE
Texas Campaign Contributions

### ISSUE THREAD

**Issue by gswider** [sketch-city/project-ideas#148]
**Project Purpose**
Campaign contribution data in Texas isn’t optimized for easy access, which prevents the public from understanding what entities may be influencing the voting patterns of their elected representatives. The lack of easy access creates even greater barriers for those who are already information- and technology-disadvantaged. How might we improve so that campaign contribution data in Texas is more accessible based on standard accessibility criteria?

**Project Objective**
Create a user-friendly queryable database and dashboards from Texas Ethics Commission campaign contribution data so the public and interested organizations can easily access and analyze this public information.  

**Core Team Roles**

_Project Manager_ (@gswider): Sets the vision of the project and manages the operations of the project. This includes onboarding new project members, keeping the project on track with goals and milestones, and delegating non-technical tasks.

_Project Lead_ (TBD): Lead technical contributor. This person will establish the best means to build out the proposed solutions.

_Public Policy Expert_ (TBD): Has familiarity with Texas campaign finance policy and data, serves as subject matter expert and can help us identify and overcome barriers to data use.

_Data Analyst_ (TBD): Manages data manipulation and organization, identifies and addresses data integrity issues, notes outstanding questions about the data that need to be taken back to TEC for clarification, assists in cleaning data, building queries, and developing the dashboard

_Data Engineer_ (TBD): Dictates the data structure and hierarchy for the database, determines what types of queries and dashboards should be built, and leads the team to build them

_Designer/Developer_ (TBD): Leads the development and execution of a dashboard tool, ensures data translates into a user-friendly end-product that meets the needs of those trying to access this data

**[Data Collaboration Workspace & Resources](https://data.world/gswider/texas-campaign-contributions)**
View our [data project on data.world](https://data.world/gswider/texas-campaign-contributions) to access the data, sample queries, team discussion threads, and links to project resources

**Comment by syedsabbas360** [comment]
I'm interested in this opportunity, please call me at 7132989471 thanks

**Comment by d-m-wilson** [comment]
I don't know how well it aligns with what you're trying to do, but I've already built a mostly-automated process (i.e. [SSIS package](https://docs.microsoft.com/en-us/sql/integration-services/integration-services-ssis-packages?view=sql-server-2017)) to load all the TEC data files into an MS SQL Server database.

**Comment by gswider** [comment]
See this repo for hackathon output managing TEC data via PostgreSQL: https://github.com/EvanCarroll/db-Texas-Ethics-Commission

**Comment by aannxxaa** [comment]
Hey! Are you guys still working on this? I'm a UX designer/researcher (not a developer unfortunately...) and I'd love to help with this project. I can plan out a user-friendly flow and wireframe the UI

**Comment by gswider** [comment]
Hello! Here's a write up we recently did about where we're at with the project and how to join the conversation to pitch in moving forward: https://medium.com/data-for-democracy/d4d-project-highlight-the-texas-beer-project-24a5ccc73053

Mostly we're looking for help with refining some data viz at this point, but would love to hear your ideas on the data.world data project or Data for Democracy slack channel (see links in the article). Cheers!

**Comment by EvanCarroll** [comment]
Just as a follow up, I moved the repo a very long time ago to,

* https://github.com/EvanCarroll/db-Texas-Ethics-Commission/

If anyone wants to play with it.
