### ISSUE TITLE
Houston Region Entrepreneurship Ecosystem Development

### ISSUE THREAD

**Issue by softintelventures** [sketch-city/project-ideas#149]
Project Sandbox

Background
With an area in excess of 625 square miles, Houston is home to the “Energy Capital of the World,” the world’s largest medical center, NASA and the Port of Houston which boasts the largest foreign tonnage in the nation. Yet, in spite of these accomplishments, Houston does not rank well on several startup indices including the Kauffman Foundation’s Metro Rankings. This was best demonstrated during the unsuccessful attempt to recruit the new Amazon Headquarters. Houston was not even in the top 20 of candidate cities.

Statement of Problem
As the fourth largest city in the nation, Houston has a unique problem set impacting the development of its entrepreneurial ecosystem: Geography – it takes too long to get to places where “serendipitous collisions” can occur. In Houston it is difficult to foster a unified healthy entrepreneurship ecosystem given the distance and the time it takes to reach entrepreneurial hubs. Compounding the distance factor, Houston has disparate affinity groups - ethnic, cultural, lingual, gender, academic - each with their respective business savvy, comfort level, availability and financial means 

Solution
In order to enable more entrepreneurial connection points, we need to create a virtual, decentralized and localized “ecosystem sandbox.” Establishing these “sandboxes” in each of Houston’s city council districts would create a pipeline for future candidates to existing and future city entrepreneurial accelerators.

Needs
The team will consist of four members and myself. The specific skill sets I am looking for are as follows:

1	Full stack developer (front end/back end)
2	Person well versed in City politics to conduct interviews with City 	entrepreneurship ecosystem stakeholders
3	Well balanced team player to conduct interviews, PowerPoint, etc.
4	Data/analytics person with access to area databases

**Comment by ahollyer** [comment]
I'm curious to learn more about your vision for this app. Are you going to pitch at the hackathon?

**Comment by softintelventures** [comment]
I will know by COB Friday if I will proceed. If I can miraculously develop a team PRIOR to the event then, yes, I would proceed. Worth noting, I just submitted a grant application for the Kauffman Foundation which, if selected in October, would be the next step on this endeavor (whether this idea wins-or-not at the hackathon). The grant application, submitted under the auspices of the the CEDC, deals with integrating regional (suburban) entrepreneurs into metro-area entrepreneurial hubs.

**Comment by LawExplorer** [comment]
Much of the discussion during this morning's [Houston Unfiltered Meetup](https://www.meetup.com/opencoffeehouston) centered on inclusion and diversity in the entrepreneurship ecosystem.  This project idea calls attention to geography as a dimension of diversity and inclusion.

**Comment by softintelventures** [comment]
I saw your proposal LawExplorer and was intrigued. Interesting solution (wikis).

**Comment by softintelventures** [comment]
AHOLLYER...update project description...Will you be there tomorrow?

**Comment by softintelventures** [comment]
AHOLLYER...updated project description...Will you be there tomorrow?
