### ISSUE TITLE
City Wiki

### ISSUE THREAD

**Issue by jessebounds** [sketch-city/project-ideas#151]
Make a dynamic and crowd-sourced wiki for City issues. The goal is to use the 311 knowledgebase that call-takers use to answer customer questions, and the City's website, to develop an open, searchable and collaborative FAQ. Data is available here: [http://data.houstontx.gov/dataset/lagan-knowledge-data-dump](http://data.houstontx.gov/dataset/lagan-knowledge-data-dump). jesse.bounds@houstontx.gov

**Comment by LawExplorer** [comment]
The relevant extension for MediaWiki is Data Transfer ([https://www.mediawiki.org/wiki/Extension:Data_Transfer](https://www.mediawiki.org/wiki/Extension:Data_Transfer)).  This is one of many [extensions](http://referata.com/wiki/Special:Version) that are available through [Referata](http://referata.com/wiki/Main_Page), which is a free wiki farm that can be used to create a prototype.

**Comment by LawExplorer** [comment]
One of the MediaWiki developers from NASA suggested that Meza ([https://www.mediawiki.org/wiki/Meza](https://www.mediawiki.org/wiki/Meza)) might be a good option for the City of Houston.
