### ISSUE TITLE
Smart City (Portland, OR) topics to examine

### ISSUE THREAD

**Issue by cyberchucktx** [sketch-city/project-ideas#155]
I'm not proposing a specific project (yet) but thought I'd pass along the efforts in Portland, Oregon to show city-sponsored civic projects. 

They have a site devoted to what they term the  [Smart City PDX" project](https://www.smartcitypdx.com/), and a [section with a  list of projects](https://www.smartcitypdx.com/projects) including: 

* Air Quality Sensor Testing & Deployment
* Infrastructure Monitoring Pilot
* Open Data Program
* [Traffic Safety Sensor Project](https://www.portlandoregon.gov/transportation/76735)

to name a few. I'm interested in the last project in particular as I'm about to get more active on my biking over the summer and this project (city-sponsored) is designed to put traffic monitors in place around the city to help make biking safer.

**Comment by IvanGabrielDiaz** [comment]
I am interested in working on this Project with you.

**Comment by cyberchucktx** [comment]
So where are you located? I'm in North Houston (Spring/Conroe).

**Comment by IvanGabrielDiaz** [comment]
Good morning,


I am located in Arlington at UTA

________________________________

**Comment by cyberchucktx** [comment]
Ah. I used to be at UTA as a research person and EE adjunct professor. 

As to a project: does Arlington (or DFW) have anything like the Open Houston group ? https://www.facebook.com/OpenHoustonGov
