### ISSUE TITLE
Cycle Houston

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#25]
Replicate [Cycle Philly](http://www.cyclephilly.org/), a smartphone-based project to collect voluntary data on cyclists’ bike route preferences. The data generated will help [the Houston Bike Plan committee](http://houstonbikeplan.org/) understand from a network perspective how bicyclists move through the city and provide another data resource to help prioritize improvements.

**Comment by juyeongkim** [comment]
[Cycle Philly Android](https://github.com/CfABrigadePhiladelphia/Cycle-Philly-Android)
[Cycle Philly iOS](https://github.com/CfABrigadePhiladelphia/CyclePhilly-iOS-app)
[Cycle Philly Backend](https://github.com/CfABrigadePhiladelphia/cyclephilly)

**Comment by juyeongkim** [comment]
Cycle Philly is based on [Cycle Atlanta](http://cycleatlanta.org/)!

[Cycle Atlanta Android](https://github.com/cledantec/Cycle-Atlanta-Android)
[Cycle Atlanta iOS](https://github.com/cledantec/Cycle-Atlanta-iOS)
[Cycle Atlanta Backend](https://github.com/cledantec/cycleatlanta.org)

**Comment by chloe8** [comment]
It's defnitely an app I'd like to work on.
Would it be possible as well to make it useful for bikeriders? I mean not only record their bikeways but also recommend the best and safest streets to bike in the city?

**Comment by colonelrascals** [comment]
I would definitely be interested in this app, my first thought would be why not use existing data through Strava's heat map? We'd have data going back to 2014, as well as a constant flow from riders like myself that use Strava on a daily basis.

**Comment by fileunderjeff** [comment]
@colonelrascals unfortunately, I believe Strava charges for its data beyond heat maps.

**Comment by lpendeavors** [comment]
I'm going for it

**Comment by colonelrascals** [comment]
if you need any help let me know. I'll be pretty preoccupied the next couple of weeks, but would be more than happy to contribute a few hours

**Comment by lpendeavors** [comment]
Progress pic:
![screenshot_20170408-153640](https://cloud.githubusercontent.com/assets/10328090/24832286/49fe514e-1c72-11e7-9ba7-f8f15a26dd36.png)

**Comment by lpendeavors** [comment]
We can go ahead and close the casket on this one.

Looking to finish up the app side of things by today or tomorrow, but here's the repo: https://github.com/lpendeavors/cycle-houston

**Comment by fileunderjeff** [comment]
Closing issue. Repo located here: https://github.com/lpendeavors/cycle-houston
