### ISSUE TITLE
Voter guide translation to Vietnamese

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#30]
Translate the League of Women Voters guide to Vietnamese.

**Comment by htruong555** [comment]
I can help with this project. Please give me some details about the project

**Comment by fileunderjeff** [comment]
@htruong555 i'll get more details today!

**Comment by htruong555** [comment]
Hi Jeff,

I missed the Hackathon but still like to help with the Vietnamese
translation project if it is still available. Please let me know if I can
get involve with it. Thanks

Truong

**Comment by fileunderjeff** [comment]
Hi @htruong555! What is your email address? You can reach me at jeff@januaryadvisors.com. I'll connect you with the League of Women Voters directly. Thanks! :)

**Comment by htruong555** [comment]
my email is htruong555@gmail.com. Thanks

Truong

**Comment by fileunderjeff** [comment]
Closing this issue as the election is over.

**Comment by htruong555** [comment]
Thanks Jeff. I'm sorry that it did not work out as we do not have time and
enough personnel for this project. However, I'm always interested in civic
projects. Please let me know if something's coming up.

Best regards,
Truong

**Comment by fileunderjeff** [comment]
No worries, @htruong555! There is always another election. We'll do a better job planning on our side next time.
