### ISSUE TITLE
Predictive analytics for homeless services

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#35]
Using publicly accessible data (such as eviction dispositions), develop a model that the Salvation Army can use to reach out to people just before they become homeless.

**Comment by melpang** [comment]
Hi Jeff-- this is my first time using this site. Would it be helpful for me start putting eviction data here? Or have you acquired data through another means? 
Thanks for including this project; I'm excited to see where it goes.

**Comment by fileunderjeff** [comment]
Hey @melpang! You can absolutely put it here. Please feel free to post links, thoughts, etc. Consider it a working notepad where we can put all sorts of things in one place to discuss.

**Comment by melpang** [comment]
Fantastic. You're the best! I'll work on figuring out the best place to start; the data is big, so I'll try to digest it a bit first. Even if no one else works on it, I'll just be happy to have this dedicated time and space. Thanks, Jeff!

**Comment by christyleos** [comment]
I'd like to work on this project as well @melpang I'm a project manager and content writer; I hope those skills would be useful to you

**Comment by melpang** [comment]
@christyleos Fantastic! I have to teach at a community gardening class (long story) this morning, but I should be there this afternoon around 1pm. Thanks for your interest and help! Maybe we can look to recruit some folks to help with visualizing the data once I can get my stuff together.

**Comment by MarvKira** [comment]
I would like to join this project too. I can work on the data visualization but I'm also open to work on other parts.

**Comment by christyleos** [comment]
Sweet; since you guys are the data visualization people, what preliminary research do you need? Or how can I support? @melpang @MarvKira (I'm at the HTC right now)

**Comment by melpang** [comment]
Awesome @marvkira ! Here's a cool project that inspires me from San Francisco: http://www.antievictionmap.com/ 
We can find all the eviction records through the Harris County Justice of the Peace Courts (http://www.jp.hctx.net/). We can get up to one month of data at a time here http://web.jp.hctx.net/PublicExtracts/request.html.  We'll have to search by each Precinct and Place and then each month of the period of time we choose.  There's a lot of data in these files, most importantly the address of eviction and the name of the landlord (or landlord representative). 
When I get there I'll try to narrow a precinct to start with using my agency's data but I just wanted to provide that context. Thanks all!

**Comment by christyleos** [comment]
Hey @MarvKira and @melpang , there is a big group here looking at homeless data as well :D I'm in the pink jacket if you are here already.

**Comment by christyleos** [comment]
hey @melpang just created a google folder, let us know when you get here

**Comment by christyleos** [comment]
We are in room 210

**Comment by melpang** [comment]
On my way!

**Comment by christyleos** [comment]
Find repository here https://github.com/christyleos/evictionanalytics
