### ISSUE TITLE
Broadband internet / fiber map

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#4]
Using the [Google Fiber checklist](https://fiber.storage.googleapis.com/legal/googlefibercitychecklist2-24-14.pdf) and available data sources from the City of Houston, build a map to navigate the gaps in Houston’s fiber backbone.

**Comment by hdub2** [comment]
This one is of particular interest to me - I live right next to downtown and have access only to DSL through AT&T.  I'm not sure what you mean by using the Google Fiber checklist though - is there a submission from Houston available somewhere?

**Comment by fileunderjeff** [comment]
@hdub2 awesome! yeah, Google Fiber has an excellent checklist here: https://fiber.storage.googleapis.com/legal/googlefibercitychecklist2-24-14.pdf

We could model the project after that, or not. Up to you!

**Comment by brianmoore180** [comment]
Hi all,

We've got several people at the Hackathon interested in this project. I'm wearing a red/teal horizontal striped shirt. Come talk to me if you're interested!

Thanks,
Brian Moore

**Comment by fileunderjeff** [comment]
We had several TPIA requests for data denied. Until that changes, this project will have to take a different form. Closing issue.
