### ISSUE TITLE
Create a content strategy for Sketch City

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#40]
We have a community of 1,600+ awesome people. We'd like to tell their stories, what matters to them, and how technology and data can help. If you've got a background in marketing, we'd love your help developing a content strategy and volunteer plan.

**Comment by klovelady** [comment]
Would definitely work on this if there were other marketers interested!

**Comment by srigdon** [comment]
I'm definitely going to be working on this between volunteer shifts this weekend. Can't wait!

**Comment by gpmelon** [comment]
Absolutely interested, let's do it!
