### ISSUE TITLE
Create a streetview dataset for analysis

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#42]
Take HCAD lot data & location data (lat/long), query the Google Maps API, grab street view images, and associate with HCAD data. 

This dataset could be fundamental for other datasets. For example, we could obtain a grant and use Mechanical Turk to analyze sidewalk conditions throughout the entire city. 

Inspired by [this guy's work](http://kotarohara.com/projects/).

**Comment by poprox** [comment]
here is a similar idea - http://solutions.arcgis.com/local-government/help/photo-survey/

it has the full spectrum of tools available to collect your own streetview photos, but could use any photos really that contain location information.  Also has a crowd-source configurable app that can be used to have people give feedback on the photos and connect that information back to the photo and the associated properties.

**Comment by fileunderjeff** [comment]
Closed. Duplicate of #18.
