### ISSUE TITLE
Lookup whether home qualifies for Residential Energy Efficiency Program (REEP)

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#44]
Create an app with address lookup that tells whether the address falls within REEP boundaries.

[REEP boundaries](http://data.houstontx.gov/dataset/city-of-houston-residential-energy-efficiency-program-locations)
[REEP program info](http://www.houstontx.gov/reep/)

**Comment by jessebounds** [comment]
The REEP program was discontinued in January 2015. Lost federal funding... Bummer!

**Comment by fileunderjeff** [comment]
Yeah, we found out after Neethi inquired! :(
