### ISSUE TITLE
Regional data portal

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#57]
It's great that the City of Houston has an open data portal. But what about all of the other government agencies that serve the same area? They publish data, too. Create a website to guide users through the various open data portals and sites (federal, state, county, city, etc.).

**Comment by ardouglass** [comment]
I know this isn't quite the same topic, but it would be awesome to just get all the data on data.gov. They have a guide on what to do here: https://www.data.gov/about#howto. It would require participation from the local agencies, but it would also skip this regional step and go right to the national level, where you can search by location, type, etc.

**Comment by fileunderjeff** [comment]
@ardouglass I agree. That suggestion requires a lot of data prep, though, since you have to be compliant with their standards. Therefore, I would recommend that you make it a suggestion in the feedback form referenced in #54.

**Comment by fileunderjeff** [comment]
Closed after creating #75
