### ISSUE TITLE
Regional Server Network for Regional Apps

### ISSUE THREAD

**Issue by randy7771026** [sketch-city/project-ideas#58]
Please describe your project, the problem you're solving, and why it's important. Keep it brief! Link to further reading if necessary.

Local code irrespective of device downloadable from local servers / as close to backbone as possible.

**Comment by fileunderjeff** [comment]
@randy7771026 can you provide more details on this project (i.e. a project goal or deliverable)? if not, can you close the issue? We can revive when there are more specifics. Thank you.
