### ISSUE TITLE
Find All The Districts API

### ISSUE THREAD

**Issue by ardouglass** [sketch-city/project-ideas#60]
**The Problem**
I can think of a handful of reasons a civic application would need to be able to look up various districts at the city, county, state, or national level. Also things like TIRZs. You should be able to provide a latlong or a county precinct number and have it return this data in a JSON/XML form for use in other applications.

**Project**
Backend interface, database, and end user API where the following can happen:
1. Admins can upload a geojson, shapefile, etc. of voting precincts with an expiration date (usually they can only change at certain times by law).
2. Admins can then upload the same for district/area/zone/whatever.
3. Code runs to build a less intense to query database mapping the larger areas down to what precincts are in them.
4. API users can make queries like `/api/geo/29.75/-95.36` or `/api/precinct/harris/0750`
5. JSON/XML spat out with known data, and a tag of some sort if it's outdated according to the expiration set.

**Why It's Important**
On it's own, it's not hugely important, but you could build all sorts of things with this data. Especially if the raw files were also provided somehow to download.

Off the top of my head, you could build the following:
- Simple district listing interface: http://whatsmydistrict.org/
- Who represents me, but like way more in depth: http://www.fyi.legis.state.tx.us/Home.aspx
- A digital clone of a voter registration card like this: [Texas voter registration card](https://cloud.githubusercontent.com/assets/1390578/15260137/bf478d78-191a-11e6-959a-c686203d0848.jpg)
- A digital version of the League of Women Voters Voter Guide, but without showing you all the stuff you can't actually vote for (the project I plan on doing next). For the primaries it was 51 pages. It took me 2 hours to get through, and at least half the time was just trying to find what was relevant to me.

**Why It Isn't Part of the Voting Project I'm Working On**
I decided to make this it's own service because it could benefit other projects easily. It also means other projects depending on it as a resource will have some skin in the game on keeping the data up to date and accurate.

**Comment by fileunderjeff** [comment]
This is a great idea, and I can see a lot of practical uses for it.

**Comment by betterways** [comment]
Yes.  Because I can never remember.

**Comment by fileunderjeff** [comment]
Repo opened: https://github.com/sketch-city/district-finder

Closing issue.

**Comment by betterways** [comment]
The Citizens' Environmental Coalition will be a good first customer.

**Comment by ardouglass** [comment]
@betterways progress is coming along. I'm working on an admin interface to make adding data sets easy, and then I'll be working on the website where users can acquire API keys, volunteer to provide data, and that sort of thing.
