### ISSUE TITLE
Housing and resources for Homeless and LGBT Youth

### ISSUE THREAD

**Issue by Edreih** [sketch-city/project-ideas#64]
Finding solutions for the high rates of homelessness in LGBT youth by raising awareness to facilitate public funding towards this project. We are creating a map on which people can find available homeless shelters and resources.

**Comment by JohnLamb87** [comment]
This is such a great idea! There are resources for these people but the problem is they are blind to them. Many of them don't know how to obtain lost records and/or get access to healthcare.

**Comment by Edreih** [comment]
@JohnLamb87 That is a great idea! We are definitely going to implement that.

**Comment by JohnLamb87** [comment]
Within the Harris Health network they individuals can receive healthcare to include dental and substance abuse counsel. Here is a link to some of the shelters and other resource centers. 

https://www.harrishealth.org/en/our-community/outreach-services/pages/healthcare-homeless.aspx

**Comment by fileunderjeff** [comment]
Active work on Slack channel.
