### ISSUE TITLE
TaskBounty

### ISSUE THREAD

**Issue by mohanrajendran** [sketch-city/project-ideas#65]
Ever had a problem where your 311 request to the city is denied or not fulfilled in a timely manner? Wish you or your fellow neighbors could hire a subcontractor to just go ahead and fix it? This tool would let you do just that. You can also view existing tasks and top up the bounties for issues you care about.

**Comment by mohanrajendran** [comment]
Git repository found at https://github.com/mohanrajendran/task-bounty

**Comment by fileunderjeff** [comment]
See git repo.
