### ISSUE TITLE
Using Pokemon to Get Out the Vote

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#68]
The League of Women Voters of the Houston Area recently applied for (and did not receive) a small amount of funding to place Pokemon lures at polling places, and drive them to signage telling them how to register. Anyone interested in helping to produce this project and raise $500? LWV Houston can partner and help recruit volunteers.

**Comment by fileunderjeff** [comment]
Instead of driving them to signage, we could also staff the polling place with volunteer deputy voter registrars and sign them up on the spot.

**Comment by christyleos** [comment]
What kind of help would you be needing specifically? This sounds like a great project!

**Comment by fileunderjeff** [comment]
@christyleos good question! I don't play Pokemon (shh!) so we'd need people who understand the game and can place lures, and the team would need to schedule when, where, who staffs it, and how we measure it. I think we can do that in 1 team meeting and try it out with a few dollars from Sketch City's funds.

**Comment by christyleos** [comment]
Playing isn't difficult at all (you should lol). All of this sounds pretty simple once an agenda is laid out. 

What will require more is the marketing to get people out there, and measuring. Or maybe not, either way count me in!

Found a few articles for those who might jump on this thread later: 
- http://www.denverpost.com/2016/07/31/colorado-pokemon-go-catch-voters/
- http://time.com/money/4408013/pokemon-go-register-to-vote/
- http://www.usnews.com/news/articles/2016-07-18/could-pokemon-go-break-election-laws this wouldn't be doing so as far as I can tell.

**Comment by fileunderjeff** [comment]
Closed, as the flash has left the pan.
