### ISSUE TITLE
Crime Stats by Neighborhood

### ISSUE THREAD

**Issue by randy7771026** [sketch-city/project-ideas#69]
I am starting to spec out with mine.

https://github.com/randy7771026/crime-stats

crime-stats

Visualize crime stats for area of Greater Northside Management District

It starts with:

http://data.ohouston.org/dataset/houston-police-department-crime-statistics

type data that Sgt. Morrison as recently as last Friday tells me is going real time. In the meanwhile the feed to:

http://houston.everyblock.com/?only=crime-reports

seems to be live again after a month on hiatus.

So all of that plus api collection of meta data from social networks but geolocated and though it looks like we can pull meta from Nextdoor

https://northsidevillagewest.nextdoor.com/news_feed/?post=29950752

because their are end points, do they want us to and should we.

**Comment by randy7771026** [comment]
Yep but not the things I still need to learn about git and github.  I have
to learn a seemless flow from local dirs to local git to github and back
again.

**Comment by randy7771026** [comment]
The github and git process has been worked around and is not seemless but does now have a reasonable stitch.  Current working page is at:

https://randy7771026.github.io/jcrime/

**Comment by fileunderjeff** [comment]
Closing. Reference repo: https://github.com/randy7771026/crime-stats
