### ISSUE TITLE
Northside Management District Crime Map

### ISSUE THREAD

**Issue by fileunderjeff** [sketch-city/project-ideas#72]
Build a lightweight, at-a-glance crime map for the police beats within the Northside Management District. This will help them understand the nature of crime in the district, and deploy their supplemental security and police accordingly.

**Comment by fileunderjeff** [comment]
@randy7771026 this was the basemap chooser for Leaflet that I couldn't find at the hack night: http://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by randy7771026** [comment]
Thanks. Note: Issue #69

and this is where I am playing.

https://github.com/randy7771026/crime-stats

 I have a lot to learn yet about git and github

**Comment by fileunderjeff** [comment]
Nope, you're right - i'll close this issue!
