### ISSUE TITLE
Airbnb

### ISSUE THREAD

**Issue by edpettitt** [sketch-city/project-ideas#95]
Find ways to scrape, mine, visualize, and manipulate data on Airbnb listings in Houston relative to their social, economic, cultural, and civil impacts.

**Comment by TylerMorrisHOU** [comment]
One really interesting idea with this -- it might be interesting to cross reference Airbnb listings in Houston with their HCAD appraisals to see how closely that correlates. Theoretically, we should expect whole-house list prices on Airbnb to correlate pretty directly with appraisals, and if that's not happening it might indicate that there's some sort of error in the appraisal.

**Comment by edpettitt** [comment]
Hi Tyler, this is a great idea. Will you be at the hackathon?  If this is something you'd like to work on, I'd be happy to partner with you.  I need folks with the programming knowledge to do the analysis.  Hope to see you at the hackathon!

**Comment by antonywu** [comment]
@TylerDMorris Do you mean houses with AirBnB should have higher appraisal values than houses without hosting AirBnB?

**Comment by RiceOwlXinTan** [comment]
In the past several weeks, I have been working on scraping and analyzing the Houston Airbnb listings. I have the cross reference between with Harvey impact data, Zillow listings, census data, and community survey data. The result is that the correlation is super low. Usually around 0.05.

**Comment by edpettitt** [comment]
Thanks for that update!  Can you email me at edpettitt@gmail.com to discuss?

Ed
